Имплементация Domain Mode
apmath-web/currency pull request #23
Opened 2019-05-25 21:41 UTC by anatolyefimov

- [ ] Создать domain model object
- [ ]   Имплементировать интерфейсы
- [ ]   Написать конструкторы для объектов

close #18

2019-05-26 19:39 UTC, malinink requested changes

2019-05-26 19:39 UTC, malinink commented on Domain/Models/ChangeTableModel.go
> +func (i ChangeTable) GetCurrencyRates() []Domain.CurrencyRate {
указатель же надо всегда использовать

2019-05-26 19:39 UTC, malinink commented on Domain/Models/CurrencyRateModel.go
> +	url := "https://api.exchangeratesapi.io/latest?symbols=" + i.wantedCurrency.GetName() + "&base=" + i.basedCurrency.GetName()
зачем это в модели?

2019-05-26 19:39 UTC, malinink commented on Domain/Models/CurrencyRateModel.go
> +	url := "https://api.exchangeratesapi.io/latest?symbols=" + i.wantedCurrency.GetName() + "&base=" + i.basedCurrency.GetName()
модель сама себя инициализировать не должна, для получения данных нужен сервис,мне кажется вы потеряли главную мысль.

2019-05-27 16:12 UTC, levkovalenko approved these changes

2019-05-27 16:14 UTC, malinink approved these changes

2019-05-27 16:14 UTC, merged