Написать mapper
apmath-web/currency pull request #30
Opened 2019-05-29 19:31 UTC by sashachernyshova

- [ ] mapper в domain model
_______________________________________________________
Добавила необходимую реализацию Domain Model
Изменила amount из int в float64

Close #19

2019-05-30 19:53 UTC, malinink requested changes

2019-05-30 19:53 UTC, malinink commented on Application/v1/viewModels/CurrencyViewModel.go
> +	Amount          float64 `json:"amount"`
мы же округляем до целого, или в `сurrency` у  нас по спецификации `float`?

2019-05-30 19:53 UTC, malinink commented on Domain/Models/CurrencyChangeModel.go
> +func (i CurrencyChangeModel) GetCurrency() Domain.Currency {
указатели!

2019-05-31 09:16 UTC, sashachernyshova commented on Application/v1/viewModels/CurrencyViewModel.go
> +	Amount          float64 `json:"amount"`
в нашей(Currency) конкретно не было, но посмотрела по остальным, вроде указали все int. Исправила

2019-05-31 09:25 UTC, sashachernyshova commented on Domain/Models/CurrencyChangeModel.go
> +func (i CurrencyChangeModel) GetCurrency() Domain.Currency {
Исправила

2019-05-31 10:45 UTC, malinink requested changes

2019-05-31 10:45 UTC, malinink commented on Domain/Models/CurrencyRateModel.go
> +	Rate           int
а вот rate float как раз

2019-05-31 10:52 UTC, malinink approved these changes

2019-05-31 10:53 UTC, merged