domain interfaces added
apmath-web/currency pull request #42
Opened 2019-06-01 16:17 UTC by anatolyefimov

2019-06-02 07:49 UTC, malinink requested changes

2019-06-02 07:49 UTC, malinink commented on Application/v1/viewModels/CurrencyViewModel.go
> +//выпилил валидацию валют, так как тперь все обрабатываем вроде
как минимум 3 буквы и upper case проверки должны быть

2019-06-02 07:49 UTC, malinink commented on Domain/repositoriesInterface.go
> +	Set(data CurrencyRateInterface) error
предлагаю `Set(from CurrencyInterface, to Currency/interface, RateInterface)`

2019-06-02 07:49 UTC, malinink commented on Domain/serviceInterface.go
> +	FetchAll() RatesInterface
не должна порождать доменную модель, сделайте ещё один интерфейс
тредлагаю тут сделать как раз 
string string float структурку

2019-06-02 07:49 UTC, malinink commented on Domain/repositoriesInterface.go
> +	Get(from string, to string) RateInterface
тут тоже CurrencyInterface заместо string

2019-06-02 07:49 UTC, malinink commented on Domain/serviceInterface.go
> +	Exchange(data CurrencyChangeInterface) float64
Возвращать `AmountInterface` (с одним полем, например `value`)

2019-06-03 06:29 UTC, malinink commented
я всёже видимо не совсем понял вашу мысль про одну ветку, давайте вначале простаилизируем интерфейсы, а все остальное в отдельных ветках

2019-06-04 05:45 UTC, malinink requested changes

2019-06-04 05:45 UTC, malinink commented on Application/v1/actions/actionCurrency.go
> +	// updater := Infrastructure.GetServiceManager().GetUpdaterService()
он же не готов, зачем тогда мне его проверять? если экшен не нужен - удалите его

2019-06-04 05:45 UTC, malinink commented on Application/v1/mapper/CurrencyMapper.go
> +	return domainModels.GenCurrencyChange(currentCurrency, wantedCurrency, amount)
как я уже писал выше, маппим мы в `string`, `string`, `float64`

2019-06-04 05:45 UTC, malinink commented on Application/v1/viewModels/CurrencyViewModel.go
> +	if len(c.WantedCurrency) != 3 {
Вынесите в отдельный метод, заччем дважды дублировать один и тот же код

2019-06-04 05:45 UTC, malinink commented on Application/v1/mapper/CurrencyMapper.go
> +func CurrencyMapper(vm viewModels.CurrencyViewModel) Domain.CurrencyChangeInterface {
непонятно зачем вам маппер, если есть гидратор в валидаторе? либо один либо вротой не нужны.

2019-06-04 05:45 UTC, malinink commented on Domain/domainModelInterface.go
> +	GetWantedCurrency() CurrencyInterface
настаиваю на стринге тут, входящий интерфейс не должен содержать доменные модели, только DTO а CurrencyChangeInterface и есть DTO

2019-06-04 05:45 UTC, malinink commented on Domain/repositoriesInterface.go
> +	Print()
зачем? Используйте дебаг для отладки вашего кода

2019-06-04 05:45 UTC, malinink commented on Domain/serviceInterface.go
> +	GetCurrency() string
давайте сделаем как договаривались на паре, тут будут пары валют и рейт

2019-06-04 05:45 UTC, malinink commented on Domain/services/ExchangerService.go
> +	fmt.Print("FromExhanger Rate", rate)
убрать отладку

2019-06-04 05:45 UTC, malinink commented on Domain/services/UpdaterService.go
> +	instance.repository.Set(
перенести логику формирования пар в `Fetcher`

2019-06-04 05:45 UTC, malinink commented on Infrastructure/repositories/Repository.go
> +	return domainModels.GenRate(repository.rates[from.GetName()][to.GetName()])
значения может не быть в массиве

2019-06-04 05:45 UTC, malinink commented on Infrastructure/repositories/Repository.go
> +	fmt.Print("=======Print repo==========\n")
уберите бесючую отладку из ваших коммитов!!!!

2019-06-04 05:45 UTC, malinink commented on Infrastructure/repositories/Repository.go
>  	once.Do(func() {
я бы эту фичу перенес в SM, это он должен разруливать подобные вещи, создавать новый экземпляр или же нет.

2019-06-04 05:45 UTC, malinink commented on Infrastructure/applicationModels/Fetcher.go
> +	// for _, obj := range fetchRates {
не нужно? убрать!

2019-06-04 07:25 UTC, anatolyefimov commented on Application/v1/mapper/CurrencyMapper.go
> +func CurrencyMapper(vm viewModels.CurrencyViewModel) Domain.CurrencyChangeInterface {
Hydrate действительно не использовали, но он для разных целей. Hydrate: Dm ---> vm

2019-06-04 15:00 UTC, malinink requested changes

2019-06-04 15:00 UTC, malinink commented on Domain/repositoriesInterface.go
> +	Print()
всё ещё тут

2019-06-04 15:00 UTC, malinink commented on Domain/services/ExchangerService.go
> +	fmt.Print("FromExhanger Rate", rate)
не убрали

2019-06-04 15:00 UTC, malinink commented on Infrastructure/repositories/Repository.go
> +	fmt.Print("=======Print repo==========\n")
отладка...

2019-06-04 15:00 UTC, malinink commented on Infrastructure/repositories/Repository.go
>  	once.Do(func() {
не перенесли?

2019-06-04 16:11 UTC, malinink requested changes

2019-06-04 16:11 UTC, malinink commented on Infrastructure/applicationModels/Fetcher.go
> +		log.Fatal(err)
никогда не сработает

2019-06-04 16:11 UTC, malinink commented on Infrastructure/repositories/Repository.go
> +	return domainModels.GenRate(repository.rates[from.GetName()][to.GetName()])
тут что?

2019-06-04 20:17 UTC, malinink submitted a review, later dismissed

2019-06-04 20:32 UTC, malinink requested changes

2019-06-04 20:32 UTC, malinink commented on Domain/Models/CurrencyChangeModel.go
> +<<<<<<< HEAD
так конфликты не резолвят =)))

2019-06-04 20:32 UTC, anatolyefimov commented on Domain/Models/CurrencyChangeModel.go
> +<<<<<<< HEAD
бывает

2019-06-04 20:41 UTC, malinink approved these changes

2019-06-04 20:41 UTC, merged